window.i18nTranslations['JA'] = {
  "title_monte": "ビルド",
  "subtitle_time": " ドリームチーム",
  "btn_idioma": "言語",
  "modal_idioma": "言語",
  "formacao": "フォーメーション",
  "estilo": "スタイル",
  "defensivo": "守備的",
  "equilibrado": "バランス",
  "ofensivo": "攻撃的",
  "roll_desc_pre": "チームとワールドカップを<br>抽選する",
  "btn_jogar": "プレイ",
  "roll_desc_mid": "新しいチームとワールドカップを<br>抽選する",
  "btn_sortear": "抽選",
  "pais": "国",
  "copa": "カップ",
  "reroll_text": "やり直す",
  "restantes": "残り",
  "btn_outra_selecao": "他の国",
  "btn_outra_copa": "他のカップ",
  "escolha_jogador": "選手を選択",
  "escalacao_completa": "スクワッド完成",
  "btn_simular": "試合をシミュレート",
  "lendas": "レジェンド",
  "lendas_desc": "歴史に名を残す<br>偉大なレジェンドたちとプレイ",
  "sua_escalacao": "あなたのスクワッド",
  "ataque": "攻撃",
  "defesa": "守備",
  "jogo_a_jogo": "試合ごと",
  "automatico": "自動",
  "velocidade_1x": "速度 1X",
  "velocidade_2x": "速度 2X",
  "velocidade_3x": "速度 3X",
  "fase_de_grupos": "グループステージ",
  "fase_eliminatoria": "ノックアウトステージ",
  "oitavas_de_final": "ラウンド16",
  "quartas_de_final": "準々決勝",
  "semifinal": "準決勝",
  "final": "決勝",
  "terceiro_lugar": "3位決定戦",
  "proximo_jogo": "次の試合",
  "proxima_fase": "次のステージ",
  "encerrar": "終了",
  "tabela_classificacao": "順位表",
  "pts": "Pts",
  "sg": "GD",
  "footer_text": "8-0は独立したプロジェクトであり、国際サッカー連盟（FIFA）との提携、承認、スポンサーシップはありません。",
  "nenhum_pais_selecionado": "国が選択されていません",
  "nenhuma_lenda_encontrada": "レジェンドが見つかりません",
  "ataque_abbr": "攻",
  "defesa_abbr": "守",
  "copa_de": "カップ",
  "forca": "強さ",
  "no_goals": "0 ゴール",
  "no_goals_desc": "試合でゴールはありませんでした。",
  "goals_for": "得点",
  "goals_against": "失点",
  "wins_single": "勝利",
  "wins_plural": "勝利",
  "draws_label": "引き分け",
  "losses_label": "敗北",
  "eliminated": "敗退",
  "advanced": "進出",
  "penalties_best_of_5": "PK戦 · ベスト・オブ・5",
  "penalties_sudden_death": "サドンデス",
  "next_game_champion": "チャンピオン",
  "phase_round32": "ラウンド32",
  "phase_round16": "ラウンド16",
  "phase_quarter": "準々決勝",
  "phase_semi": "準決勝",
  "phase_final": "決勝",
  "match_end": "終了",
  "pen_indicator": "PK戦",
  "next_game_knockout": "ノックアウト",
  "next_game_new": "新しいゲーム",
  "next_game_next_phase": "次の試合",
  "next_game_eliminated": "新しいゲーム",
  "Centroavante": "センターフォワード",
  "Goleiro": "ゴールキーパー",
  "Lateral-direito": "右サイドバック",
  "Lateral-esquerdo": "左サイドバック",
  "Meia": "ミッドフィルダー",
  "Meia-direita": "右ミッドフィルダー",
  "Meia-esquerda": "左ミッドフィルダー",
  "Meio-campista": "ミッドフィルダー",
  "Ponta-direita": "右ウイング",
  "Ponta-esquerda": "左ウイング",
  "Volante": "守備的ミッドフィルダー",
  "Zagueiro": "センターバック",
  "GOL": "GK",
  "LD": "RB",
  "LE": "LB",
  "ZAG": "CB",
  "VOL": "CDM",
  "MC": "CM",
  "MD": "RM",
  "ME": "LM",
  "PD": "RW",
  "PE": "LW",
  "ATA": "ST",
  "CA": "ST",
  "MEI": "CAM",
  "Alemanha": "ドイツ",
  "Argentina": "アルゼンチン",
  "Argélia": "アルジェリア",
  "Austrália": "オーストラリア",
  "Brasil": "ブラジル",
  "Bulgária": "ブルガリア",
  "Bélgica": "ベルギー",
  "Camarões": "カメルーン",
  "Chile": "チリ",
  "Colômbia": "コロンビア",
  "Coreia do Sul": "韓国",
  "Costa Rica": "コスタリカ",
  "Costa do Marfim": "コートジボワール",
  "Croácia": "クロアチア",
  "Dinamarca": "デンマーク",
  "Egito": "エジプト",
  "Equador": "エクアドル",
  "Escócia": "スコットランド",
  "Espanha": "スペイン",
  "Estados Unidos": "アメリカ",
  "França": "フランス",
  "Gana": "ガーナ",
  "Grécia": "ギリシャ",
  "Holanda": "オランダ",
  "Hungria": "ハンガリー",
  "Inglaterra": "イングランド",
  "Irlanda": "アイルランド",
  "Irlanda do Norte": "北アイルランド",
  "Itália": "イタリア",
  "Iugoslávia": "ユーゴスラビア",
  "Japão": "日本",
  "Marrocos": "モロッコ",
  "México": "メキシコ",
  "Nigéria": "ナイジェリア",
  "Paraguai": "パラグアイ",
  "País de Gales": "ウェールズ",
  "Peru": "ペルー",
  "Polônia": "ポーランド",
  "Portugal": "ポルトガル",
  "Romênia": "ルーマニア",
  "Rússia": "ロシア",
  "Senegal": "セネガル",
  "Suécia": "スウェーデン",
  "Suíça": "スイス",
  "Sérvia": "セルビア",
  "Tchecoslováquia": "チェコスロバキア",
  "Tchéquia": "チェコ",
  "Turquia": "トルコ",
  "Ucrânia": "ウクライナ",
  "União Soviética": "ソビエト連邦",
  "Uruguai": "ウルグアイ",
  "Áustria": "オーストリア",
  "POSIÇÃO": "ポジション",
  "POSIÇÕES": "ポジション",

  sua_selecao: 'あなたのチーム', classificado: '通過', eliminado: '敗退', avancou_de_fase: '進出', simulando: 'シミュレーション中...', gol_scored: 'ゴール', gols_scored: 'ゴール', sofreu_goals: '失点', paises_selecionados: '選択された国',
  start_title: 'あなたは<span style="color: #2b8fe8;">8-0</span>で勝てますか？',
  start_subtitle: 'チームとカップを抽選し、各ポジションに選手を配置して、あなたのチームが8-0で勝てるか確かめよう。',
  start_play_btn: 'プレイ',
  how_to_play: 'プレイ方法',
  how_to_desc: '<div class="how-to-columns"><div class="how-to-col"><div class="how-to-sec"><h4>プレイ方法</h4><p>抽選で国とワールドカップを決定します。そのチームから選手を選び、ラインナップの空いているポジションに配置します。</p><p>各選手は1回しか使えません。空いているポジションに合わない場合は使用できません。</p></div><div class="how-to-sec"><h4>やり直し</h4><p>ラウンドごとに限られた回数だけやり直せます。現在のチームに戦術や残りのポジションに合う選手がいない場合に使ってください。</p></div></div><div class="how-to-col"><div class="how-to-sec"><h4>最適化のポイント</h4><p>個人の能力だけを追い求めないでください。勝つチームには、守備の安定感、創造的な中盤、速いウイング、そしてバランスの取れたダイナミックな攻撃が必要です。</p></div><div class="how-to-sec"><h4>勝利</h4><p>すべてのポジションが埋まると、ゲームはあなたのチームのトーナメントをシミュレートします。</p><p>目標は8連勝して無敗のチャンピオンになることです！</p></div></div></div>'
};

window.i18nTranslations['RU'] = {
  "title_monte": "СОЗДАТЬ",
  "subtitle_time": " КОМАНДУ МЕЧТЫ",
  "btn_idioma": "ЯЗЫК",
  "modal_idioma": "ЯЗЫК",
  "formacao": "ФОРМАЦИЯ",
  "estilo": "СТИЛЬ",
  "defensivo": "Оборонительный",
  "equilibrado": "Сбалансированный",
  "ofensivo": "Атакующий",
  "roll_desc_pre": "Играть, чтобы выбрать сборную<br>и Чемпионат мира",
  "btn_jogar": "ИГРАТЬ",
  "roll_desc_mid": "Выбрать новую сборную<br>и Чемпионат мира",
  "btn_sortear": "ЖЕРЕБЬЕВКА",
  "pais": "СТРАНА",
  "copa": "КУБОК",
  "reroll_text": "НЕ НРАВИТСЯ? ПЕРЕИГРАТЬ",
  "restantes": "ОСТАЛОСЬ",
  "btn_outra_selecao": "ДРУГАЯ СТРАНА",
  "btn_outra_copa": "ДРУГОЙ КУБОК",
  "escolha_jogador": "ВЫБЕРИТЕ ИГРОКА",
  "escalacao_completa": "СОСТАВ ГОТОВ",
  "btn_simular": "СИМУЛИРОВАТЬ МАТЧ",
  "lendas": "ЛЕГЕНДЫ",
  "lendas_desc": "Играйте с величайшими легендами<br>в истории",
  "sua_escalacao": "ВАШ СОСТАВ",
  "ataque": "АТАКА",
  "defesa": "ЗАЩИТА",
  "jogo_a_jogo": "МАТЧ ЗА МАТЧЕМ",
  "automatico": "АВТОМАТИЧЕСКИ",
  "velocidade_1x": "СКОРОСТЬ 1X",
  "velocidade_2x": "СКОРОСТЬ 2X",
  "velocidade_3x": "СКОРОСТЬ 3X",
  "fase_de_grupos": "ГРУППОВОЙ ЭТАП",
  "fase_eliminatoria": "ПЛЕЙ-ОФФ",
  "oitavas_de_final": "1/8 ФИНАЛА",
  "quartas_de_final": "ЧЕТВЕРТЬФИНАЛ",
  "semifinal": "ПОЛУФИНАЛ",
  "final": "ФИНАЛ",
  "terceiro_lugar": "МАТЧ ЗА 3-Е МЕСТО",
  "proximo_jogo": "СЛЕДУЮЩИЙ МАТЧ",
  "proxima_fase": "СЛЕДУЮЩИЙ ЭТАП",
  "encerrar": "ЗАВЕРШИТЬ",
  "tabela_classificacao": "ТАБЛИЦА",
  "pts": "Очки",
  "sg": "РГ",
  "footer_text": "8-0 — это независимый проект, не имеющий связей, поддержки или спонсорства со стороны Международной федерации футбола (FIFA).",
  "nenhum_pais_selecionado": "Страна не выбрана",
  "nenhuma_lenda_encontrada": "Легенды не найдены",
  "ataque_abbr": "Атк",
  "defesa_abbr": "Защ",
  "copa_de": "Кубок",
  "forca": "Сила",
  "no_goals": "0 ГОЛОВ",
  "no_goals_desc": "В матче не было голов.",
  "goals_for": "ЗАБИТЫЕ ГОЛЫ",
  "goals_against": "ПРОПУЩЕННЫЕ ГОЛЫ",
  "wins_single": "ПОБЕДА",
  "wins_plural": "ПОБЕДЫ",
  "draws_label": "НИЧЬИ",
  "losses_label": "ПОРАЖЕНИЯ",
  "eliminated": "ВЫБЫЛ",
  "advanced": "ПРОШЕЛ",
  "penalties_best_of_5": "СЕРИЯ ПЕНАЛЬТИ · ЛУЧШИЙ ИЗ 5",
  "penalties_sudden_death": "МГНОВЕННАЯ СМЕРТЬ",
  "next_game_champion": "ЧЕМПИОН",
  "phase_round32": "1/16 ФИНАЛА",
  "phase_round16": "1/8 ФИНАЛА",
  "phase_quarter": "ЧЕТВЕРТЬФИНАЛ",
  "phase_semi": "ПОЛУФИНАЛ",
  "phase_final": "ФИНАЛ",
  "match_end": "КОНЕЦ",
  "pen_indicator": "ПЕНАЛЬТИ",
  "next_game_knockout": "ПЛЕЙ-ОФФ",
  "next_game_new": "НОВАЯ ИГРА",
  "next_game_next_phase": "СЛЕДУЮЩИЙ МАТЧ",
  "next_game_eliminated": "НОВАЯ ИГРА",
  "Centroavante": "Центрфорвард",
  "Goleiro": "Вратарь",
  "Lateral-direito": "Правый защитник",
  "Lateral-esquerdo": "Левый защитник",
  "Meia": "Полузащитник",
  "Meia-direita": "Правый полузащитник",
  "Meia-esquerda": "Левый полузащитник",
  "Meio-campista": "Полузащитник",
  "Ponta-direita": "Правый вингер",
  "Ponta-esquerda": "Левый вингер",
  "Volante": "Опорный полузащитник",
  "Zagueiro": "Центральный защитник",
  "GOL": "ВРТ",
  "LD": "ПЗ",
  "LE": "ЛЗ",
  "ZAG": "ЦЗ",
  "VOL": "ОП",
  "MC": "ЦП",
  "MD": "ПП",
  "ME": "ЛП",
  "PD": "ПВ",
  "PE": "ЛВ",
  "ATA": "ФРВ",
  "CA": "ЦФ",
  "MEI": "ЦАП",
  "Alemanha": "Германия",
  "Argentina": "Аргентина",
  "Argélia": "Алжир",
  "Austrália": "Австралия",
  "Brasil": "Бразилия",
  "Bulgária": "Болгария",
  "Bélgica": "Бельгия",
  "Camarões": "Камерун",
  "Chile": "Чили",
  "Colômbia": "Колумбия",
  "Coreia do Sul": "Южная Корея",
  "Costa Rica": "Коста-Рика",
  "Costa do Marfim": "Кот-д'Ивуар",
  "Croácia": "Хорватия",
  "Dinamarca": "Дания",
  "Egito": "Египет",
  "Equador": "Эквадор",
  "Escócia": "Шотландия",
  "Espanha": "Испания",
  "Estados Unidos": "США",
  "França": "Франция",
  "Gana": "Гана",
  "Grécia": "Греция",
  "Holanda": "Нидерланды",
  "Hungria": "Венгрия",
  "Inglaterra": "Англия",
  "Irlanda": "Ирландия",
  "Irlanda do Norte": "Северная Ирландия",
  "Itália": "Италия",
  "Iugoslávia": "Югославия",
  "Japão": "Япония",
  "Marrocos": "Марокко",
  "México": "Мексика",
  "Nigéria": "Нигерия",
  "Paraguai": "Парагвай",
  "País de Gales": "Уэльс",
  "Peru": "Перу",
  "Polônia": "Польша",
  "Portugal": "Португалия",
  "Romênia": "Румыния",
  "Rússia": "Россия",
  "Senegal": "Сенегал",
  "Suécia": "Швеция",
  "Suíça": "Швейцария",
  "Sérvia": "Сербия",
  "Tchecoslováquia": "Чехословакия",
  "Tchéquia": "Чехия",
  "Turquia": "Турция",
  "Ucrânia": "Украина",
  "União Soviética": "СССР",
  "Uruguai": "Уругвай",
  "Áustria": "Австрия",
  "POSIÇÃO": "ПОЗИЦИЯ",
  "POSIÇÕES": "ПОЗИЦИИ",

  sua_selecao: 'ВАША СБОРНАЯ', classificado: 'КВАЛИФИЦИРОВАН', eliminado: 'ВЫБЫЛ', avancou_de_fase: 'ПРОШЕЛ', simulando: 'Симуляция...', gol_scored: 'ГОЛ', gols_scored: 'ГОЛОВ', sofreu_goals: 'ПРОПУЩЕНО', paises_selecionados: 'ВЫБРАННЫЕ СТРАНЫ',
  start_title: 'ВЫ СМОЖЕТЕ ДОСТИЧЬ <span style="color: #2b8fe8;">8-0</span>?',
  start_subtitle: 'Выберите сборную и кубок, расставьте игроков по позициям и узнайте, сможет ли ваша команда выиграть 8-0.',
  start_play_btn: 'ИГРАТЬ',
  how_to_play: 'КАК ИГРАТЬ?',
  how_to_desc: '<div class="how-to-columns"><div class="how-to-col"><div class="how-to-sec"><h4>Как играть</h4><p>Вращайте, чтобы выбрать страну и Чемпионат мира. Выберите игрока из этого состава и поместите его на свободную подходящую позицию.</p><p>Каждого игрока можно использовать только один раз. Если игрок не подходит ни на одну свободную позицию, он будет недоступен.</p></div><div class="how-to-sec"><h4>Переигровки</h4><p>У вас есть ограниченное количество переигровок в течение раунда. Используйте их, если в текущем составе нет игроков, подходящих вашей тактической схеме или оставшимся позициям.</p></div></div><div class="how-to-col"><div class="how-to-sec"><h4>Что оптимизировать</h4><p>Не гонитесь только за индивидуальной статистикой. Командам-победительницам нужна стабильная защита, креативная полузащита, быстрые вингеры и динамичная атака, работающая как единое целое.</p></div><div class="how-to-sec"><h4>Победа</h4><p>После того, как все позиции будут заполнены, игра симулирует кампанию вашей команды на турнире.</p><p>Ваша цель - выиграть 8 матчей подряд и стать непобежденным чемпионом!</p></div></div></div>'
};
